
development:
  adapter: postgresql
  encoding: utf8
  database: hashtag_muncher_dev
  template: template0
  host: localhost
  port: 5432
  pool: 5
  username: jay
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: hashtag_muncher_test
  template: template0
  host: localhost
  port: 5432
  pool: 5
  username: jay
  password:
